name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: -Xmx4g
    steps:
      - uses: actions/checkout@v3.5.2

      - uses: actions/setup-java@v3.11.0
        with:
          distribution: 'adopt'
          java-version: '17'

      - uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: build
