name: Publish

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: -Xmx4g
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: gradle/actions/setup-gradle@v3

      - run: ./gradlew publishPlugin
        env:
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}

      - name: Get Release Name
        id: release_name
        run: |
          RELEASE_NAME=${{ github.ref }}
          RELEASE_NAME=${RELEASE_NAME#refs/tags/v}
          echo "name=${RELEASE_NAME}" >> "$GITHUB_OUTPUT"

      - uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.release_name.outputs.name }}
          body: 'draft'
          files: './build/distributions/*'
          draft: true
